namespace VaccPet.Helpers.Models
{
    public class Animal
    {
        public int Key { get; set; }
        public string Value { get; set; }

        public List<Animal> GetAllAnimals()
        {
            return new List<Animal>()
            {
                new Animal{Key = 1, Value = "Cachorro"},
                new Animal{Key = 2, Value = "Gato"},
                new Animal{Key = 3, Value = "Peixe"},
                new Animal{Key = 4, Value = "Ave"},
                new Animal{Key = 5, Value = "Coelho"},
                new Animal{Key = 6, Value = "Hamster"},
                new Animal{Key = 7, Value = "Tartaruga"},
                new Animal{Key = 8, Value = "Porquinho-da-índia"},
                new Animal{Key = 9, Value = "Furão"},
                new Animal{Key = 10, Value = "Chinchila"},
                new Animal{Key = 11, Value = "Rato"},
                new Animal{Key = 12, Value = "Gerbil"},
                new Animal{Key = 13, Value = "Cobra"},
                new Animal{Key = 14, Value = "Lagarto"},
                new Animal{Key = 15, Value = "Cavalo"},
                new Animal{Key = 16, Value = "Porco"},
            };
        }
        public List<Animal> GetBreedDogs()
        {
            return new List<Animal>()
            {
                new Animal{Key = 1, Value =  "Afghan Hound"},
                new Animal{Key = 2, Value =  "Airedale Terrier"},
                new Animal{Key = 3, Value =  "Akita"},
                new Animal{Key = 4, Value =  "Akita Inu"},
                new Animal{Key = 5, Value =  "Alaskan Malamute"},
                new Animal{Key = 6, Value =  "American Bulldog"},
                new Animal{Key = 7, Value =  "American Staffordshire Terrier"},
                new Animal{Key = 8, Value =  "Anatolian Shepherd"},
                new Animal{Key = 9, Value =  "Australian Cattle Dog"},
                new Animal{Key = 10, Value = "Australian Shepherd"},
                new Animal{Key = 11, Value = "Basset Hound"},
                new Animal{Key = 12, Value = "Basenji"},
                new Animal{Key = 13, Value = "Beagle"},
                new Animal{Key = 14, Value = "Bernese Mountain Dog"},
                new Animal{Key = 15, Value = "Bichon Frisé"},
                new Animal{Key = 16, Value = "Bloodhound"},
                new Animal{Key = 17, Value = "Border Collie"},
                new Animal{Key = 18, Value = "Border Terrier"},
                new Animal{Key = 19, Value = "Boston Terrier"},
                new Animal{Key = 20, Value = "Boxer"},
                new Animal{Key = 21, Value = "Bull Terrier"},
                new Animal{Key = 22, Value = "Bulldog Francês"},
                new Animal{Key = 23, Value = "Bullmastiff"},
                new Animal{Key = 25, Value = "Cairn Terrier"},
                new Animal{Key = 26, Value = "Cane Corso"},
                new Animal{Key = 27, Value = "Cavalier King Charles Spaniel"},
                new Animal{Key = 28, Value = "Chihuahua"},
                new Animal{Key = 29, Value = "Chinese Crested"},
                new Animal{Key = 30, Value = "Chow Chow"},
                new Animal{Key = 31, Value = "Clumber Spaniel"},
                new Animal{Key = 32, Value = "Cocker Spaniel"},
                new Animal{Key = 33, Value = "Collie"},
                new Animal{Key = 34, Value = "Dachshund (Teckel)"},
                new Animal{Key = 35, Value = "Dalmatian"},
                new Animal{Key = 36, Value = "Dobermann Pinscher"},
                new Animal{Key = 37, Value = "Doberman"},
                new Animal{Key = 38, Value = "English Cocker Spaniel"},
                new Animal{Key = 39, Value = "English Setter"},
                new Animal{Key = 40, Value = "French Bulldog"},
                new Animal{Key = 41, Value = "German Shorthaired Pointer"},
                new Animal{Key = 42, Value = "Golden Retriever"},
                new Animal{Key = 43, Value = "Gordon Setter"},
                new Animal{Key = 44, Value = "Great Dane"},
                new Animal{Key = 45, Value = "Great Pyrenees"},
                new Animal{Key = 46, Value = "Greyhound"},
                new Animal{Key = 47, Value = "Husky Siberiano"},
                new Animal{Key = 48, Value = "Irish Setter"},
                new Animal{Key = 49, Value = "Irish Terrier"},
                new Animal{Key = 50, Value = "Irish Wolfhound"},
                new Animal{Key = 51, Value = "Italian Greyhound"},
                new Animal{Key = 52, Value = "Japanese Chin"},
                new Animal{Key = 53, Value = "Kuvasz"},
                new Animal{Key = 54, Value = "Labrador Retriever"},
                new Animal{Key = 55, Value = "Leonberger"},
                new Animal{Key = 56, Value = "Lhasa Apso"},
                new Animal{Key = 57, Value = "Maltese"},
                new Animal{Key = 58, Value = "Mexican Hairless"},
                new Animal{Key = 59, Value = "Miniature Pinscher"},
                new Animal{Key = 60, Value = "Newfoundland"},
                new Animal{Key = 61, Value = "Norwegian Elkhound"},
                new Animal{Key = 62, Value = "Norwich Terrier"},
                new Animal{Key = 63, Value = "Old English Sheepdog"},
                new Animal{Key = 64, Value = "Papillon"},
                new Animal{Key = 65, Value = "Pekingese"},
                new Animal{Key = 66, Value = "Pembroke Welsh Corgi"},
                new Animal{Key = 67, Value = "Pomeranian"},
                new Animal{Key = 68, Value = "Portuguese Water Dog"},
                new Animal{Key = 69, Value = "Pug"},
                new Animal{Key = 70, Value = "Rhodesian Ridgeback"},
                new Animal{Key = 71, Value = "Rottweiler"},
                new Animal{Key = 72, Value = "Saint Bernard"},
                new Animal{Key = 73, Value = "Samoyed"},
                new Animal{Key = 74, Value = "Schnauzer Miniatura"},
                new Animal{Key = 75, Value = "Scottish Terrier"},
                new Animal{Key = 76, Value = "Shar Pei"},
                new Animal{Key = 77, Value = "Shetland Sheepdog"},
                new Animal{Key = 78, Value = "Shiba Inu"},
                new Animal{Key = 79, Value = "Shih Tzu"},
                new Animal{Key = 80, Value = "Staffordshire Bull Terrier"},
                new Animal{Key = 81, Value = "Staffordshire Bull Terrier"},
                new Animal{Key = 82, Value = "Tibetan Mastiff"},
                new Animal{Key = 83, Value = "Tibetan Spaniel"},
                new Animal{Key = 84, Value = "Tibetan Terrier"},
                new Animal{Key = 85, Value = "Toy Fox Terrier"},
                new Animal{Key = 86, Value = "Vizsla"},
                new Animal{Key = 87, Value = "Weimaraner"},
                new Animal{Key = 88, Value = "Welsh Springer Spaniel"},
                new Animal{Key = 89, Value = "West Highland White Terrier"},
                new Animal{Key = 90, Value = "Whippet"},
                new Animal{Key = 91, Value = "Yorkshire Terrier"},
                new Animal{Key = 92, Value = "Poodle"},
                new Animal{Key = 93, Value = "Sem Raça Definida"},
            };
        }
        public List<Animal> GetBreedCats()
        {
            return new List<Animal>()
            {
                new Animal{Key = 1, Value =  "Burmilla"},
                new Animal{Key = 2, Value =  "California Spangled"},
                new Animal{Key = 3, Value =  "Chausie"},
                new Animal{Key = 4, Value =  "Chartreux"},
                new Animal{Key = 5, Value =  "Chinchila"},
                new Animal{Key = 6, Value =  "Cornish Rex"},
                new Animal{Key = 7, Value =  "Cymric"},
                new Animal{Key = 8, Value =  "Devon Rex"},
                new Animal{Key = 9, Value =  "Don Sphynx"},
                new Animal{Key = 10, Value = "Egyptian Mau"},
                new Animal{Key = 11, Value = "Europeu Comum"},
                new Animal{Key = 12, Value = "Exótico de Pelo Curto"},
                new Animal{Key = 13, Value = "Nebelung"},
                new Animal{Key = 14, Value = "Norueguês da Floresta"},
                new Animal{Key = 15, Value = "Ocicat"},
                new Animal{Key = 16, Value = "Oriental"},
                new Animal{Key = 17, Value = "Persa"},
                new Animal{Key = 18, Value = "Peterbald"},
                new Animal{Key = 19, Value = "Pixie-Bob"},
                new Animal{Key = 20, Value = "Ragamuffin"},
                new Animal{Key = 21, Value = "Ragdoll"},
                new Animal{Key = 22, Value = "Sagrado da Birmânia"},
                new Animal{Key = 23, Value = "Savannah"},
                new Animal{Key = 25, Value = "Scottish Fold"},
                new Animal{Key = 26, Value = "Selkirk Rex"},
                new Animal{Key = 27, Value = "Serengeti"},
                new Animal{Key = 28, Value = "Siamês"},
                new Animal{Key = 29, Value = "Siberiano"},
                new Animal{Key = 30, Value = "Singapura"},
                new Animal{Key = 31, Value = "Snowshoe"},
                new Animal{Key = 32, Value = "Somali"},
                new Animal{Key = 33, Value = "Sphynx"},
                new Animal{Key = 34, Value = "Tonquinês"},
                new Animal{Key = 35, Value = "Toyger"},
                new Animal{Key = 36, Value = "Turco Van"},
                new Animal{Key = 37, Value = "Ural Rex"},
                new Animal{Key = 38, Value = "York Chocolate"},
                new Animal{Key = 39, Value = "Sem Raça Definida"},

            };
        }
        public List<Animal> GetBreedBirds()
        {
            return new List<Animal>()
            {
                new Animal{Key = 1, Value =  "Agapornis"},
                new Animal{Key = 2, Value =  "Alma-de-gato"},
                new Animal{Key = 3, Value =  "Andorinha-de-rio"},
                new Animal{Key = 4, Value =  "Anu-branco"},
                new Animal{Key = 5, Value =  "Anu-preto"},
                new Animal{Key = 6, Value =  "Aracuã"},
                new Animal{Key = 7, Value =  "Arara-azul"},
                new Animal{Key = 8, Value =  "Arara-canindé"},
                new Animal{Key = 9, Value =  "Arara-vermelha"},
                new Animal{Key = 10, Value = "Beija-flor"},
                new Animal{Key = 11, Value = "Bem-te-vi"},
                new Animal{Key = 12, Value = "Bentevizinho"},
                new Animal{Key = 13, Value = "Bigodinho"},
                new Animal{Key = 14, Value = "Caboclinho"},
                new Animal{Key = 15, Value = "Calopsita"},
                new Animal{Key = 16, Value = "Canário-belga"},
                new Animal{Key = 17, Value = "Canário-da-terra"},
                new Animal{Key = 18, Value = "Cardeal"},
                new Animal{Key = 19, Value = "Coleirinho"},
                new Animal{Key = 20, Value = "Curió"},
                new Animal{Key = 21, Value = "Gaivota"},
                new Animal{Key = 22, Value = "Garça-branca"},
                new Animal{Key = 23, Value = "Gavião"},
                new Animal{Key = 24, Value = "Gavião-carcará"},
                new Animal{Key = 25, Value = "Graúna"},
                new Animal{Key = 26, Value = "Jaburu"},
                new Animal{Key = 27, Value = "Jacuaçu"},
                new Animal{Key = 28, Value = "Jaçanã"},
                new Animal{Key = 29, Value = "Jandaia"},
                new Animal{Key = 30, Value = "João-de-barro"},
                new Animal{Key = 31, Value = "Juriti"},
                new Animal{Key = 32, Value = "Maracanã"},
                new Animal{Key = 33, Value = "Martim-pescador"},
                new Animal{Key = 34, Value = "Mergulhão"},
                new Animal{Key = 35, Value = "Mestiço"},
                new Animal{Key = 36, Value = "Papagaio"},
                new Animal{Key = 37, Value = "Papagaio-do-mar"},
                new Animal{Key = 38, Value = "Pardal"},
                new Animal{Key = 39, Value = "Periquito"},
                new Animal{Key = 40, Value = "Pica-pau"},
                new Animal{Key = 41, Value = "Pombo"},
                new Animal{Key = 42, Value = "Quero-quero"},
                new Animal{Key = 43, Value = "Rouxinol"},
                new Animal{Key = 44, Value = "Sabiá"},
                new Animal{Key = 45, Value = "Sanhaço"},
                new Animal{Key = 46, Value = "Saracura"},
                new Animal{Key = 47, Value = "Saracura-três-potes"},
                new Animal{Key = 48, Value = "Serinus"},
                new Animal{Key = 49, Value = "Siriema"},
                new Animal{Key = 50, Value = "Suindara"},
                new Animal{Key = 51, Value = "Tico-tico"},
                new Animal{Key = 52, Value = "Tucano"},
                new Animal{Key = 53, Value = "Tucano-de-bico-preto"},
                new Animal{Key = 54, Value = "Tucano-de-bico-verde"},
                new Animal{Key = 55, Value = "Urutau"},
                new Animal{Key = 56, Value = "Uruvu-preto"},
                new Animal{Key = 57, Value = "Xexéu"},

            };
        }
    }
}
